# Generated by Django 3.2.3 on 2021-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
