# Generated by Django 3.2.3 on 2021-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_ordermodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
