# Generated by Django 3.2.3 on 2021-07-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_alter_ordermodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
